if: tag IS blank

cache:
  yarn: true
  directories:
    - node_modules

language: node_js
node_js:
 - '10'
 - '8'
 - '6'

before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install: npm install
